### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nakulz** [Future-Scholars/paperlib#603]
**Describe the bug**
RSS Feeds do not refresh

**To Reproduce**
1. Go to Feeds
2. Right Click on any rss feed that you might have added previously
3. Scroll down to click 'Refresh'
4. Pop-up in the bottom left corner of the app  that says  
"Feed
Failed to refresh feeds: ai
TypeError: e is not iterable at l4.parseRSSItems (file:///Applications/Paperlib.app/Contents/Res...
"

**Screenshots or Log**
21:26:08.958 › [Feed] Failed to refresh feeds: ai
21:26:08.958 › TypeError: e is not iterable
    at l4.parseRSSItems (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-f93563e5.js:16:4258)
    at l4.parse (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-f93563e5.js:16:4139)
    at l4.fetch (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-f93563e5.js:16:3861)
    at async n (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-f93563e5.js:16:10306)
    at async file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-744bc545.js:395:59031
    at async Promise.allSettled (index 0)
    at async i81 (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-744bc545.js:395:58970)
    at async rr.refresh (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-f93563e5.js:16:10286)
    at async a.constructor.name.i.value (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-744bc545.js:56:42943)
    at async o.constructor.name.s.value (file:///Applications/Paperlib.app/Contents/Resources/app.asar/dist/assets/index-744bc545.js:56:52837)

**System (please complete the following information):**
 - OS: macOS Sonoma 14.6.1
 - Paperlib Version 3.1.9 (3.1.9)

**Additional context**
I absolutely love this application. It will be awesome if you guys can 1) add a "refresh all" feeds option and 2) improve the documentation associated with RSS feeds.

**Comment by GeoffreyChen777** [comment]
I cannot reproduce this bug.

I guess the reason is related to your RSS source.

You don't need to refresh manually. The RSS Feeds are automatically refreshed every day.

**Comment by nakulz** [comment]
Hi. That's strange. I have done nothing new since I updated the app so I'm wondering what's unique about my setup that might be causing the feeds to break. Anything I can share to try and triangulate?

BTW this is the 2-3 time this issues has happened. Previous times that it happened, I basically removed and traded all the feeds again.

**Comment by GeoffreyChen777** [comment]
You can give me an example from your subscribed RSS URL.

**Comment by nakulz** [comment]
I wanted to include the link  in the bug I filed but I'm not aware of how the url for a subscribed feed can be viewed/copied. Can u tell me how I can do that?

**Comment by GeoffreyChen777** [comment]
1. open developer tool

![image](https://github.com/user-attachments/assets/9ca7aff1-1696-400e-9d7b-36c83a09c793)

2. input: `(await feedService.load("name", "desc")).toJSON();`, press enter

![image](https://github.com/user-attachments/assets/900359b3-bac3-4d5d-8a23-1d942a77c24d)

**Comment by GeoffreyChen777** [comment]
I'm going to close this as it's inactive for a while. feel free to reopen.

**Comment by JunzheShen** [comment]
> You can give me an example from your subscribed RSS URL.

Hi, thanks for your great work! I believe I've encountered the same problem as in this issue, and my RSS URL is `https://rss.arxiv.org/rss/cs`

**Comment by tinynag** [comment]
Apologies for commenting on a closed issue, but I believe I’ve identified a way to reproduce the bug.

The issue occurs when an RSS feed contains only a single item. This happens frequently for me, as I use several custom feeds that return only the articles I need. These feeds work correctly in other RSS readers, such as Reeder on macOS, but not in Paperlib.

I suspect the parser fails because there’s no list for it to iterate over when only one feed item is present. Below is an example XML to illustrate the issue:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>Hacker News: Newest</title>
    <link>https://news.ycombinator.com/newest</link>
    <description>Hacker News RSS</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Thu, 30 Jan 2025 07:41:46 +0000</lastBuildDate>
    <item>
      <title>Apple researchers reveal the secret sauce behind DeepSeek AI</title>
      <link>https://www.zdnet.com/article/apple-researchers-reveal-the-secret-sauce-behind-deepseek-ai/</link>
    </item>
  </channel>
</rss>
```

**Comment by GeoffreyChen777** [comment]
> Apologies for commenting on a closed issue, but I believe I’ve identified a way to reproduce the bug.
> 
> The issue occurs when an RSS feed contains only a single item. This happens frequently for me, as I use several custom feeds that return only the articles I need. These feeds work correctly in other RSS readers, such as Reeder on macOS, but not in Paperlib.
> 
> I suspect the parser fails because there’s no list for it to iterate over when only one feed item is present. Below is an example XML to illustrate the issue:
> 
> <?xml version='1.0' encoding='UTF-8'?>
> <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
>   <channel>
>     <title>Hacker News: Newest</title>
>     <link>https://news.ycombinator.com/newest</link>
>     <description>Hacker News RSS</description>
>     <docs>http://www.rssboard.org/rss-specification</docs>
>     <generator>python-feedgen</generator>
>     <lastBuildDate>Thu, 30 Jan 2025 07:41:46 +0000</lastBuildDate>
>     <item>
>       <title>Apple researchers reveal the secret sauce behind DeepSeek AI</title>
>       <link>https://www.zdnet.com/article/apple-researchers-reveal-the-secret-sauce-behind-deepseek-ai/</link>
>     </item>
>   </channel>
> </rss>

@tinynag Thanks, will fix soon
